name: Feature Request
description: Suggest an improvement or new feature
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: Describe the feature and why it would be useful.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or other approaches you've tried.
